# Generated by Django 4.1.6 on 2023-03-14 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_main',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Фото+модель'),
        ),
    ]
