# Generated by Django 4.1.6 on 2023-03-15 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_product_image_add_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_10',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-10'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-3'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-4'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-5'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-6'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_7',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-7'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_8',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-8'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_9',
            field=models.ImageField(blank=True, null=True, upload_to='product', verbose_name='Изображение-9'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
