# Generated by Django 4.1.6 on 2023-03-15 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_9',
        ),
    ]
