# Generated by Django 4.1.6 on 2023-04-02 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_product_image_1_product_image_10_product_image_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image_9',
        ),
    ]
